version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - deploy:
          command: bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/circle2/scripts/upload)