version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
    test:
      - run:
          name: test
          command: npm test
      - run:
          name: Black Duck CoPilot
          command: bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/circle/scripts/upload)
